version: '3.7'
services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres
    env_file:
      - ./.env

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: db
