version: '3.7'
services:
  contracts:
    command: ./build.sh
    build:
      context: ./contracts.near-linkdrop
      dockerfile: Dockerfile
    volumes:
      - ./contracts.near-linkdrop:/app

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: yarn next dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres
    env_file:
      - ./.env

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: db
